ErikCH/DevYouTubeList

README.md
He is maintainer of [Serenity OS](https://github.com/SerenityOS/serenity) live streaming and he had some nice section called Comute Talk too when he answer subscriber questions / giving update / insight.
=> Add Andreas Kling

README.md
**Qirolab** is the tutorial channel on Laravel, Javascript, VueJs, React, etc.
**Adam Wathan** does live coding on Laravel and Tailwind CSS. And he is also the creator of Tailwind CSS.
=> Added Qirolab and Adam Wathan's youtube channel

README.md
Fixes #2 
Add some Russian YouTube channel.
=> Add Category Non English 

README.md
Python programming tutorials, machine learning, data analysis, web development etc
=> Added sentdex channel

README.md
LowLevelJavascript explains the low-level programming and under the hood layers of javascript
=> Added low-level-javascript channel

README.md
Front-end development channel. Not active now...
=> Added Ihatetomatoes channel

README.md
Fixed some typos and added DesignCourse in Tutorial resources.
=> Fixed some typos and added DesignCourse

README.md
Do streams on YouTube and Twitch that eventually end up on the YouTube
channel linked.
Thanks.
=> add Alexander Alemayhu channel

README.md
I've added a new category for competitive programming, some of the channels are very rare (although I've only added the ones by top competitive programmers)
=> Added new category for competitive programming

README.md
My first pull request. Added some few Hindi Youtube Developers Channel. I hope it is accepted
=> Added Hindi Channel 

README.md
add some brazilian channels 🇧🇷:
- BrazilJS
- Felipe Deschamps
- Rocketseat
- DevPrimata
- balta.io
- Curso em Vídeo
=> add brazilian channels

README.md
- Added **French** category 
- Added **Grafikart** channel under French category
=> Added French category, Grafikart channel, OverSeas Media channel

README.md
- Added period marks at the end of each '>' where they were missing, so that the document is more consistent.
- Changed two occurrances of 'then' to 'than' where it was grammatically incorrect.
=> Grammar and Consistency fixes in README.md

README.md
=> update live stream

README.md
This channel provides flutter tutorials.
=> Added "Mtech viral" youtube channel

README.md
- Added Real Python to the tutorials list.
Real Python offers detailed and high-quality written tutorials and has started converting them to video courses, too.
=> Added Real Python

README.md
Add JustForFunc (ran by @campoy) to retired. No idea if he'll start using the channel more, but it is an excellent resource for learning not just the Go programming language, but Google Cloud Platform, Docker, gRPC, thought process behind writing applications, and much more.
=> Add JustForFunc

README.md
A little uncertain as to which category to put this in. It is an amalgamation of a tutorial, informational, programming, and entertainment.
The channel is geared towards finding and understanding exploits such as zero days, how they work, how they can be prevented, "info security" if you will, but also contains a lot of valuable low-level & general programming information.
=> Add LiveOverflow

README.md
Channel currently has ~170 videos.
=> Added Codepunk YouTube channel

README.md
added machine learning tutorials of raqeeb,dimik computing school,tamim shahriar on Bengali list...
added yuri,abdul bari on tutorials
added kevin naughton jr,nick white,anthony,keep on coding,jackson gabbard,tech dummies-narendra l on competitive programming and interview sections
=> updated the curated list

README.md
Update for C++ Game Development/ Tutorial/ Entertainment channel.
Alias OneLoneCoder
=> Update Informational list

README.md
I've added an Arabic language with few channels that focuses on web development and apps development.
I'll be adding more whenever I find a remarkable and worthy of following channels.
=> New Language Added

README.md
Hi, i am Indonesian developer.
I hope this will help all of developers in my country.
Thank you.
=> Add Indonesian

README.md
Adding 5 Indonesian developer Youtube channels.
=> Add Indonesian Dev YT Channel

README.md
add some korean channels, HOWLAB and 레트로 retr0 and 안드로이드 생존코딩
=> add some korean channels, HOWLAB and 레트로 retr0 and 안드로이드 생존코딩

.github/workflows/check-links.yml, README.md
This should hopefully capture any broken links or invalid urls.
Reference: https://github.com/marketplace/actions/markdown-link-check
=> github: add action for checking the markdown links

.editorconfig, .gitattributes
Add `.editorconfig` and `.gitattributes` files.
=> Add .editorconfig and .gitattributes files.

README.md
Shameless plug for my channel :) 
I focus on DevOps, Kubernetes, Docker, Linux, Python, and Go
=> Add Lee Gaines

README.md
I've added eight new channels and two new sub categories for different types of DevOps.
=> Eight New Channels

README.md
I'm working on growing a youtube channel as well, so I'm adding myself to up and coming
=> Adding my channel

README.md
Would love to have my Youtube channel here as well. I focus on Front end. Much React stuff and code along tutorials with a fun touch. =)
=> Added Weibenfalk to the list

README.md
Add new channel focus in web development but above all Angular. 
LANG: Spanish
=> Add new channel DOMINICODE

README.md
Added my channel to developers list. I have made tutorials mainly using python and pygame but am planning to make more and will continue to update the channel.
=> Added one developer in tutorials

README.md
I added a new source (mine) - I hope it doesn't go against the rules if any
=> up and coming source

README.md
Just shamelessly dropping my relatively new channel into this list. 👍
=> Added The Renegade Coder to English Tutorials

README.md
=> Add ResoCoder channel

README.md
I would like to add my own YouTube channel to the list shamelessly. I cover .NET programming tutorials since 2018, and I'm committed to producing more content in 2020.
=> Add Claudio Bernasconi

README.md
Added Prismic, their YouTube channel has a lot of good informational interviews about various software topics
=> Added Prismic channel

README.md
FilledStacks by Dane Mackier  (@filledstacks) is an awesome channel for flutter and I think its worth being in the list.
=> Add FilledStacks channel

README.md
This channel has 14.4K subscribers and 388 videos.
=> add dcode channel

README.md
Added Telusko, kudvenkat, Awais Mirza in 'Tutorial'.
Added BBarters in 'Retired'.
Moved JavaBrains from 'Informational' to 'Tutorial'.
Created 'Game Development' section (moved there youtubers already existing in the list and added new ones too).
Added Jarvis Johnson in 'Software Entertainment'.
=> Added new channels, Created 'Game Development' section

README.md
Hi @ErikCH 😃,
Kent is an youtuber that does mostly coding livestreams and maintains a couple open source projects (e.g. [React Testing Library](https://github.com/testing-library/react-testing-library)). What do you think of adding him to the youtube list?
Thanks.
=> Add Kent C. Dodds to Live Coding

README.md
Kossie Coder channel provides Laravel and Vuejs tutorials in Korean
=> Add Kossie Coder youtube channel - Korean

README.md
Channel in English mainly focused on Laravel and Vue development.
=> Add Coder's Tape channel

README.md
These channels are very good . I have learnt a lot from them.
=> Some bengali youtube channels are added .

README.md
Add getCodingKnowledge to french youtubers.
Channel : https://www.youtube.com/channel/UCUjo_IKa9Cqkx_x-rMly8MA
He has a lot of little series on React, Vue, HTML, CSS, Bootstrap, JavaScript...
=> Add getCodingKnowledge to french youtubers

README.md
I post every week, I mostly talk about web development.
=> New Language, Somali

README.md
It was added my channel on the list.
=> Eduardo Albuquerque Channel

README.md
Very new channel (<100 subs), writes his own Ruby to C compiler live. Uploads frequently.
=> Add Tim Morgan

README.md
Thanks, Erik for the wonderful resource of developers who have YouTube channels!
=> Adding Dan Vega to the English Tutorial list

README.md
[Alessandro Castellani](https://www.youtube.com/user/williamprey) teaches Laravel, WordPress developement, and many more.
=> Add Alessandro Castellani

README.md
I added some channels to Tutorial, Informational, Up And Coming and Retired.
- [Code With Andrea](https://www.youtube.com/channel/UCrTnsT4OYZ53l0QGKqLeD5Q/videos)
- [DarkCode](https://www.youtube.com/channel/UCD3KVjbb7aq2OiOffuungzw/videos)
- [Devefy](https://www.youtube.com/channel/UC9dwxEAvy-zCMAS7rdox46w/videos)
- [Inspire UI](https://www.youtube.com/user/minhcasi/videos)
- [CodingWithMitch](https://www.youtube.com/channel/UCoNZZLhPuuRteu02rh7bzsw/videos)
- [Kelvin Mai](https://www.youtube.com/channel/UCUSpT2b4x2Bq3RcAAg4hFng)
- [Code Artistry](https://www.youtube.com/channel/UC-kHm7pG884IYQiYwqJWv9A/videos)
- [Coders Hub](https://www.youtube.com/channel/UCIDlA0FJcpqJHELzdelFAWg/videos)
- [FlutterDeveloper](https://www.youtube.com/channel/UCa-t2GBQ4UcbDi4vIIwagDg/videos)
=> Add some channels

README.md
NetMentor channel provides .NET and web dev tutorials in Spanish.
=> Add NetMentor channel - Spanish

README.md
This is a new PR because I force pushed to clean out the old history.
Also, I'm now listing in the main category because I passed 1k subscribers.
And I'm not sure if tutorial is the best description for my channel, but it seemed close enough for now.
=> Add Context Free

README.md
All contents in the channel are in english, spanish and catalan.
https://www.youtube.com/channel/UCoKrqNpyxBb6UQUoOQBhndg
=> Added AlbiaSoft channel about generic software programming tutorials

README.md
=> Add new channel

README.md
=> Update spanish content

README.md
I don't think I fit the requirements for 'Up And Coming' anymore so I moved myself to 'Tutorial'
=> Moving channel to different category

README.md
I added my channel to the up and coming. can we merge?
=> Adding TheDevWay

README.md
I wrote an invalid url, sorry!
=> Fixed AlbiaSoft channel URL

README.md
=> add-two-channels: add Aida Drogan and Maksim Ivanov

README.md
Added Nick Janetakis to Up And Coming.
Removed duplicate channel 'Real Python'.
=> Added Nick Janetakis to Up And Coming

README.md
Jack Herrington works with latest stacks and produces great tutorials as well as live sessions
=> Add Jack Herrington 

README.md
https://www.youtube.com/c/marceldempers
Great DevOps resources there!
=> Add @marcel-dempers Youtube channel

README.md
=> Add Vuelancer & Recoding youtube channels

README.md
Add 4 Vietnamese channels. Thanks for creating this list.
=> Add Vietnamese channels about coding

README.md
takeUforward or better known as striver_79 on competitive programming sites is a CodeChef 6-star coder and a Candidate Master on CodeForces. He is an instructor for popular computer science portal, GeeksForGeeks, as well. He creates content on cracking top product based companies and tutorials for his curated list of questions.
Links:
[CodeChef](https://www.codechef.com/users/striver_79)
[CodeForces](https://codeforces.com/profile/striver_79)
=> Add takeUforward to competitive programming list

README.md
* Adem Ilter -> Front-end
* Ugur Aktas -> Front-end
* Burhan Yilmaz -> React Native
* Devrim Gunduz -> PostgreSQL
* Fikret Cevik -> Front-end
* Serif Gungor -> Java / Android
* Mehmet Dursun Ince -> Cyber Security
=> added Turkish Youtube channels I followed

README.md
- Added **TechWorld with Nana** and **Pretty Printed**
- Removed all duplicate channels that were in the 'Artificial Intelligence and Machine Learning' section
=> Added two channels and removed duplicates

README.md
I added one chanel in __Software Entertainment__ which is _Jarvis Johnson! GOLD_, he recently said on Instagram that he's going to be using it these days and two channels in __Informational__ which are _GitHub_ &  _GitHub Training & Guides).
=> Additional of 3 channels

README.md
veryacademy is an up and new channel for python and django and python learners.
=> added veryacademy

README.md
Website Learners have one of the best WordPress/website related tutorials, and Will Kwan has some really cool AI/ML/SWE related content.
=> Adding one tutorial and one informational channel

README.md
Added another new Bengali javascript dev youtube channel
=> Added another new bengali channel

README.md
=> Added Hopson (https://www.youtube.com/channel/UCeQhZOvNKSBRU0Mdg7V44wA) to Game Dev channels

README.md
=> Move The New Boston from Retired to Tutorial

README.md
Jhankar Mahbub is a big Bengali YouTuber with 266k subs. He does programming videos on Web Dev Python and others. Added him to the Bengali YouTuber List.
=> Addded another Bengali YouTuber

README.md
Updated with Amine M. Boulouma Python Programming Youtube Channel in the section tutorials
=> Updated with Amine M. Boulouma Python Programming Youtube Channel

README.md
Andrew is the creator of [Zig](https://ziglang.org/) Programming Language.
=> Update Andrew Kelly's channel

README.md
Casual conversations about software engineering - in casual Bangla.
=> Add TechTong as a Bengali Youtube Channel

README.md
added channel 'The Exception Handler' that has intended to provide a tutorial on languages like Golang, Vue.js, Angular, NodeJs, MongoDB, and many more.
Currently working on different videos on Golang, and soon will start publishing on other languages as well.
=> Added 'The Exception Handler' in Tutorial list

README.md
added **codewithsadee** channel
=> added codewithsadee

README.md
Randy (Thomas Randall) makes amazing videos on game development, more specifically, he makes his own indie game from scratch and documents the process in a very funny way.
I hope, many people might find that stuff is very entertaining.
=> Add link to Randy channel
